name: Renovate
on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4
      - uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200  # v46.1.20
        with:
          configurationFile: renovate.json
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
